### ISSUE TITLE
AT - error

### ISSUE THREAD

**Issue by hbaileylxd** [cgkineo/adapt-hint#2]
Sorry Matt - "Missing required 'schema.subSchema' option for Object editor" when I go in to edit the component. No rush.

**Comment by moloko** [comment]
Well, I've no idea what that error means - but having had a good check through I've spotted one very obvious problem - it had been defined in bower.json as a component, but it's actually an extension.

I've fixed that now - fingers crossed that was the source of the problem...!

**Comment by hbaileylxd** [comment]
Testing now x

**Comment by hbaileylxd** [comment]
Getting somewhere.....

Ah ha - seems to be working now... I see the ? icons on my components. Are there any settings for it? They don't seem to come into Project Settings or Configuration Settings. I do see the option to Add a Hint Item for each component, but not the ability to turn it on/off per component or change the icon?

hahaha yeah just gone into an existing course and EVERY component has a hint icon! Bit overwhelming!! Had to turn it off for that project.

**Comment by hbaileylxd** [comment]
BTW this is an AWESOME plugin - just what was needed!

**Comment by moloko** [comment]
OK I suspect what's happening is that the AT was adding an empty `_hint` property to all components. I've made an amend that should fix this, could you give it another try?

**Comment by moloko** [comment]
Actually having just conferred with m'colleague @tomgreenfield he says that the AT will add a `_hint` object to all components no matter what I do in the properties.schema; this is therefore going to need a patch in the code to stop it from showing when `_hint` is empty - or an `_isEnabled` property adding. 

Any preference?

**Comment by hbaileylxd** [comment]
Well, as long as the _isEnabled is set to False as default that would be ok, but I guess having it just not showing at all unless you type something in the box is cleverererer, and means less clicks to get what you want. If that's feasible I would say that's the winner.

**Comment by moloko** [comment]
cool, could you send me a sample of the .json you have? I'd like to check exactly how the AT adds in the object so that I can ensure I code specifically for that

**Comment by hbaileylxd** [comment]
config.json from the course build? or course.json?

**Comment by moloko** [comment]
components.json please

**Comment by hbaileylxd** [comment]
yeah, or that one! 

``` json
  {
    "_id": "56dee981012883441b702e51",
    "_parentId": "56dee981012883441b702e21",
    "_type": "component",
    "_layout": "left",
    "body": "<p>You&#39;ve now reached the end of the course - have you fully read and understood everything? Check your progress bars for each section and remember you can now visit each individual section whenever you like for a refresher.</p>\n",
    "displayTitle": "",
    "title": "Component title",
    "_isOptional": false,
    "_classes": "",
    "_component": "text",
    "_pageLevelProgress": {
      "_isEnabled": false
    },
    "_search": {
      "keywords": ""
    },
    "_hint": [],
    "instruction": ""
  },
```

**Comment by moloko** [comment]
could you also send me an example of one where you have populated it with a hint? I might as well check that I set that bit up right while I'm looking at this

**Comment by hbaileylxd** [comment]
sure :)

``` json
 {
    "_id": "56eabc48aea882bc174296ac",
    "_parentId": "56dee981012883441b702e12",
    "_type": "component",
    "_layout": "right",
    "body": "",
    "displayTitle": "",
    "title": "Welcome",
    "_isOptional": false,
    "_classes": "",
    "_component": "graphic",
    "_pageLevelProgress": {
      "_isEnabled": true
    },
    "_search": {
      "keywords": ""
    },
    "_hint": [
      {
        "body": "Hello this is the hint body text",
        "title": "This is the hint title"
      }
    ],
    "_graphic": {
      "attribution": "",
      "small": "course/en/assets/b0d1c7476825c413730ac961f8fa11abfe8890bf.gif",
      "large": "course/en/assets/b0d1c7476825c413730ac961f8fa11abfe8890bf.gif",
      "alt": ""
    },
    "instruction": ""
  },
```

**Comment by hbaileylxd** [comment]
Stil showing if there is no hint added

**Comment by moloko** [comment]
should be fixed with the latest update - could you test and let us know?

**Comment by hbaileylxd** [comment]
Sure can - always happy to test things - you know that :)

**Comment by hbaileylxd** [comment]
Works REALLY well now. The _only_ thing I would say is that if you have Triggered enabled on the same component, then it overlays the Hide button as seen below. I guess if you wanted both you would have to set varaible location for the Hide button in triggered so you can move it out of the way.

But without triggered - it's a total win. One question - is it easy/possible to change the ? icon to something else as it stands? Thanks so much guys - fantastic stuff!!!

![image](https://cloud.githubusercontent.com/assets/11558341/14744162/722a9fb8-089d-11e6-8b6e-5a621864e249.png)

**Comment by moloko** [comment]
ah yes, that is an unfortunate clash with triggered... we probably also need to think about more with things like about how to configure them solely using the AT.

You can certainly change the icon but currently you have to do this by editing hint.hbs. If you want to change it to the lightbulb icon you can see in the README then do this:
![2016-04-22 15_28_39-winmerge - hint hbs-rev82 svn000 tmp hbs - hint hbs-rev83 svn000 tmp hbs](https://cloud.githubusercontent.com/assets/1249597/14744706/c7d661ca-089f-11e6-8e0d-1030786a7bc2.png)

**Comment by hbaileylxd** [comment]
awesome - happy to do that for now. Is it from the font-awesome icon set?

Super super super :)

**Comment by moloko** [comment]
> Is it from the font-awesome icon set?

Not a clue, sorry...!
