### ISSUE TITLE
Click displays default notify pop-up

### ISSUE THREAD

**Issue by illuminate-tcaffelle** [cgkineo/adapt-hint#22]
### Subject of the issue/enhancement/features
When adding to a component instead of the original notification of "expanding" from the buttons location, it uses the Adapt default notification

### Your environment
* version (AT/Framework): 5.32.5 No authoring tool being used
* which browser and its version: Chrome: 118.0.5993.72/ Firefox 118.0.2
* device(s) + operating system(s): Windows 10 desktop

### Steps to reproduce
Installed plugin and added to component.

### Expected behaviour
Should display the popup that "expands" from the location of the button

### Actual behaviour
Default Adapt Notify is used

### Screenshots (if you can)

I was able to revert back to version 3.0.0 of the plugin and got the desired functionality. Not sure if this was an un-logged change. The framework and additional plugins have not been modified. The components that had a hint attached to them were default adapt-contrib-text components. Also confirmed that the components that had "__hint"  in them were not blank and had at least a title, body, or instruction information. 

Let me know if you have any questions or if more information is needed.

**Comment by kirsty-hames** [comment]
Hi @illuminate-tcaffelle, the switch to use Notify for the Hint popup was made in this PR https://github.com/cgkineo/adapt-hint/pull/15. The main drive was to improve the accessible experience as well as allowing us to use any Notify functionality. Apologies this wasn't clear in the release notes.
