### ISSUE TITLE
Prepend hint element for accessiblity

### ISSUE THREAD

**Issue by simondate** [cgkineo/adapt-hint#7]
Currently, the hint extension is added to the end of the component it is placed in. But with the CSS used it shows in the top of the element.

For accessibility purposes, this is confusing and leads to jumping around the component. It would make sense to add the component to the start of the component or, even better, attach it to the component title (assuming there is one).

**Comment by kirsty-hames** [comment]
I agree, it's misleading the button is positioned at the top of the component yet its rendered after the component. The on screen button position should align with the reading order as per [WCAG C27: Making the DOM order match the visual order](https://www.w3.org/TR/WCAG20-TECHS/C27.html).

I typically see this plugin being used for question components to provide additional content to support answering a question. Based on this I would expect the button to display and read between the component display text and the interaction (`component__widget`). Does anyone else have other use cases that require a different location to append the hint button?

In addition, moving the hint button so it's not a direct child of the component would also resolve #6. 


<img width="840" alt="question_hint_example" src="https://github.com/cgkineo/adapt-hint/assets/7045330/10005b2c-138a-44b7-a20f-2f85fd611b27">
